version: "3"

services:
  subscriptions-api:
    build:
        context: ../
        dockerfile: dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"

  # Dependencies can go here as seperate service. For example service for storage.
  